### PR TITLE
fix: allow filtering using `Not blank` operator

### LINKED ISSUE #77: Filter by "Not blank" is not working
It looks like #40 solved only the problem for the "Blank" filter, but not for "Not blank". There's no such test indeed.

### PR DESCRIPTION
**Pull request by wandering-tales**
Fixes #77.

As per [AG Grid doc](https://www.ag-grid.com/react-data-grid/filter-text/#text-filter-options), the operator is named `Not blank` (lower `b`).

### CODE REVIEW

**Comment by wandering-tales** [comment]
Some unrelated test is failing. Could someone point me out where the issue might be?

**Comment by kpmck** [comment]
Hey @wandering-tales thanks for opening up this PR - I will take a look at the test real quickly.

**Comment by kpmck** [comment]
This is part of [3.3.2 release](https://github.com/kpmck/cypress-ag-grid/releases/tag/v3.3.2) 🎉

**Comment by wandering-tales** [comment]
Out of curiosity, why was the build failing? 🙂

**Comment by kpmck** [comment]
@wandering-tales it ended up being that a newer version of Ag Grid package was having some difficulty instantiating the agGrid object. We use a link to unpkg for the purpose of tests, and it was failing to fetch the proper object(s), and so it was failing on the before hook of the tests 😅 .

**Pull request merged**
