### PR TITLE
Add Support for ag grid 31.0.0

### LINKED ISSUE #57: Add support for ag-grid 31.0.0
Currently ag-grid 31.0.0 is not supported. I will create a pull request with support for ag-grid 31.0.0

### PR DESCRIPTION
**Pull request by air2**
This should fix #57

### CODE REVIEW

**Comment by kpmck** [comment]
Thanks so much for putting this up! I will merge to unblock you, and will work on adding more explicit waits after filters are applied so we can then remove the `.wait()` commands.

**Comment by kpmck** [comment]
This change has been published as part of [v3.0](https://github.com/kpmck/cypress-ag-grid/releases/tag/v3.0.0)

**Comment by air2** [comment]
Thanks for the quick release, I think the extra waits have to do with the now default row animations. So maybe it is possible to know when the animation is finished.

**Comment by kpmck** [comment]
I do have some of those waits baked into a solution I built using this package, so I can move that logic over this way and have it wait for the grid to fully load the grid or show an empty one, if that is expected. Thank you again!

**Pull request merged**
